// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Deckboy Contributors
// This file is part of Deckboy, a cue deck for live events.
// See LICENSE for details.

// ============================================================================
// constants.hpp — Application-wide constants and theme colors.
//
// Included by nearly every source file (via types.hpp → constants.hpp).
// All values are at global scope (no namespace) for drop-in convenience.
//
// Three categories:
//   1. UI dimensions — control window, output preview, column widths, row heights
//   2. Theme colors  — the DMG Game Boy palette (mutable for runtime theming)
//   3. Layout system — grid spacing, panel sizes, button geometry
//
// The version strings come from deckboy_version.hpp, which is generated by
// CMake from the VERSION file at the project root.
// ============================================================================

#ifndef DECKBOY_CORE_CONSTANTS_HPP
#define DECKBOY_CORE_CONSTANTS_HPP

#include "deckboy_version.hpp"    // auto-generated: kVersion, kVersionTag

#include <cstddef>
#include <cstdint>
#include <string_view>

// ---------------------------------------------------------------------------
// UI dimensions — sizes for the control window and cue list columns.
//
// kControlWidth/Height: initial size of the operator control window.
// kOutputWidth/Height:  resolution of the inline output preview panel.
// kSidebarWidth:        right-side inspector panel width.
// kColWidth/kRowHeight: cue list column and row sizing.
// kPadding:             general inner padding for UI elements.
// ---------------------------------------------------------------------------
constexpr int kControlWidth = 1760;    // control window default width (pixels)
constexpr int kControlHeight = 1020;   // control window default height (pixels)
constexpr int kOutputWidth = 1280;     // inline output preview width (pixels)
constexpr int kOutputHeight = 720;     // inline output preview height (pixels)
constexpr int kSidebarWidth = 460;     // inspector sidebar width (pixels)
constexpr int kColWidth = 270;         // cue list column width (pixels)
constexpr int kColHeaderH = 66;        // cue list column header height
constexpr int kColFooterH = 50;        // cue list column footer height
constexpr int kGlobalHeaderH = 64;     // top toolbar / global header height
constexpr int kRowHeight = 80;         // cue list row height (pixels)
constexpr int kPadding = 24;           // general inner padding (pixels)

// ---------------------------------------------------------------------------
// Audio constants — used by MediaEngine and SDL audio initialization.
//
// kAudioRate:     sample rate for all audio decode and playback (48 kHz).
// kAudioChannels: channel count (stereo). ffmpeg is told to output this layout.
// ---------------------------------------------------------------------------
constexpr int kAudioRate = 48000;      // audio sample rate (Hz) — broadcast standard
constexpr int kAudioChannels = 2;      // stereo output (all decode is mixed to stereo)

// ---------------------------------------------------------------------------
// Media pipeline — frame buffer depth for the video decode ring buffer.
//
// kMaxVideoFrames: how many decoded frames can queue before the decode thread
// blocks. Higher values smooth playback but increase memory use (~6 MB each
// at 1920x1080 RGBA). 6 frames ≈ 200ms of buffering at 30fps.
// ---------------------------------------------------------------------------
constexpr size_t kMaxVideoFrames = 6;

// ---------------------------------------------------------------------------
// Theme colors — DMG Game Boy 4-tone palette (default theme).
//
// Format: 0xRRGGBBAAu (SDL-style packed RGBA as uint32).
// These are intentionally non-const (inline, not constexpr) so that a theme
// asset pack or runtime configuration can overwrite them before first use.
//
// The palette is split into shell (case/bezel) and screen (LCD content) tones.
// All UI drawing in render/primitives.* and the app_render_*.ipp files
// reference these values for consistent theming.
// ---------------------------------------------------------------------------
inline std::uint32_t kShellOuterColor   = 0xC4CFA1FFu;  // case plastic     (196,207,161)
inline std::uint32_t kShellInnerColor   = 0xA5B088FFu;  // inner case       (165,176,136)
inline std::uint32_t kShellShadowColor  = 0x5A6B4AFFu;  // case shadow      (90,107,74)
inline std::uint32_t kScreenLightColor  = 0x9BBC0FFFu;  // LCD lightest     (155,188,15) — highlight
inline std::uint32_t kScreenMidColor    = 0x8BAC0FFFu;  // LCD mid          (139,172,15) — accent
inline std::uint32_t kScreenDarkColor   = 0x306230FFu;  // LCD dark         (48,98,48)   — body text
inline std::uint32_t kScreenDeepColor   = 0x0F380FFFu;  // LCD deepest      (15,56,15)   — background
inline std::uint32_t kScreenInkSoftColor= 0x4A7A2AFFu;  // soft ink         (74,122,42)  — secondary text
inline std::uint32_t kButtonBezelColor  = 0x7B8B5EFFu;  // button rim       (123,139,94)
inline std::uint32_t kDeleteBezelColor  = 0x8B3A3AFFu;  // danger red bezel (139,58,58)  — delete actions

// ---------------------------------------------------------------------------
// Layout system — grid-based spacing constants used by render/layout.hpp.
//
// All panels, buttons, and text insets snap to multiples of kLayoutSpacingUnit
// (8px grid). This ensures consistent vertical rhythm and alignment.
// ---------------------------------------------------------------------------
constexpr int kLayoutSpacingUnit = 8;        // base grid unit (all spacing is a multiple)
constexpr int kLayoutPanelPadding = 16;      // inner padding within panels (2 × grid)
constexpr int kLayoutPanelGap = 12;          // gap between adjacent panels
constexpr int kLayoutPanelBorder = 2;        // panel border stroke width
constexpr int kLayoutTextInset = 12;         // text inset from panel edge
constexpr int kLayoutHeaderHeight = 56;      // panel header bar height (7 × grid)
constexpr int kLayoutBottomBarHeight = 132;  // bottom control bar height
constexpr int kLayoutButtonHeight = 48;      // standard button height (6 × grid)
constexpr int kLayoutButtonPadding = 12;     // button internal horizontal padding
constexpr int kLayoutButtonGap = 8;          // gap between adjacent buttons (1 × grid)

// ---------------------------------------------------------------------------
// App identity strings — title bar, version display, about dialog.
//
// kAppVersion and kAppVersionTag are forwarded from the CMake-generated
// deckboy_version.hpp (sourced from the VERSION file at project root).
// ---------------------------------------------------------------------------
constexpr std::string_view kAppTitle = "Deckboy";
constexpr std::string_view kOutputTitle = "Deckboy Output";
constexpr std::string_view kAppVersion = deckboy::core::version::kVersion;
constexpr std::string_view kAppVersionTag = deckboy::core::version::kVersionTag;

#endif
