// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Deckboy Contributors
// This file is part of Deckboy, a cue deck for live events.
// See LICENSE for details.

// ============================================================================
// constants.hpp — Application-wide constants and theme colors.
//
// Included by nearly every source file (via types.hpp → constants.hpp).
// All values are at global scope (no namespace) for drop-in convenience.
//
// Three categories:
//   1. UI dimensions — control window, output preview, column widths, row heights
//   2. Theme colors  — the DMG Game Boy palette (mutable for runtime theming)
//   3. Layout system — grid spacing, panel sizes, button geometry
//
// The version strings come from deckboy_version.hpp, which is generated by
// CMake from the VERSION file at the project root.
// ============================================================================

#ifndef DECKBOY_CORE_CONSTANTS_HPP
#define DECKBOY_CORE_CONSTANTS_HPP

#include "deckboy_version.hpp"    // auto-generated: kVersion, kVersionTag

#include <cstddef>
#include <cstdint>
#include <string_view>

// ---------------------------------------------------------------------------
// UI dimensions — sizes for the control window and cue list columns.
//
// kControlWidth/Height: initial size of the operator control window.
// kOutputWidth/Height:  resolution of the inline output preview panel.
// kSidebarWidth:        right-side inspector panel width.
// kColWidth/kRowHeight: cue list column and row sizing.
// kPadding:             general inner padding for UI elements.
// ---------------------------------------------------------------------------
constexpr int kControlWidth = 1760;    // control window default width (pixels)
constexpr int kControlHeight = 1020;   // control window default height (pixels)
constexpr int kOutputWidth = 1280;     // inline output preview width (pixels)
constexpr int kOutputHeight = 720;     // inline output preview height (pixels)
constexpr int kSidebarWidth = 460;     // inspector sidebar width (pixels)
constexpr int kColWidth = 270;         // cue list column width (pixels)
constexpr int kColHeaderH = 66;        // cue list column header height
constexpr int kColFooterH = 50;        // cue list column footer height
constexpr int kGlobalHeaderH = 64;     // top toolbar / global header height
constexpr int kRowHeight = 80;         // cue list row height (pixels)
constexpr int kPadding = 24;           // general inner padding (pixels)

// ---------------------------------------------------------------------------
// Audio constants — used by MediaEngine and SDL audio initialization.
//
// kAudioRate:     sample rate for all audio decode and playback (48 kHz).
// kAudioChannels: channel count (stereo). ffmpeg is told to output this layout.
// ---------------------------------------------------------------------------
constexpr int kAudioRate = 48000;      // audio sample rate (Hz) — broadcast standard
constexpr int kAudioChannels = 2;      // stereo output (all decode is mixed to stereo)

// ---------------------------------------------------------------------------
// Media pipeline — frame buffer depth for the video decode ring buffer.
//
// kMaxVideoFrames: how many decoded frames can queue before the decode thread
// blocks. Higher values smooth playback but increase memory use (~6 MB each
// at 1920x1080 RGBA). 6 frames ≈ 200ms of buffering at 30fps.
// ---------------------------------------------------------------------------
constexpr size_t kMaxVideoFrames = 6;

// How many decks a show file may ask for.
//
// The loader used to create a deck for whatever index a record named, with no
// upper bound -- and every deck gets a hidden window, a renderer and its OWN
// AUDIO DEVICE at startup. A show file saying `deck 9999` therefore asked the
// machine for ten thousand audio devices and the application stopped answering
// before it finished. Found by feeding the loader a deliberately corrupt show;
// it is one mistyped field away from a hand-edited file.
//
// Sixteen is far above any real show -- VJ mode wants two -- and small enough
// that the worst case is merely slow.
constexpr int kMaxDecks = 16;

// And how many outputs, for the same reason: an output record names its index
// too, and every output gets a window and a renderer.
constexpr int kMaxOutputs = 16;

// ---------------------------------------------------------------------------
// Theme colors — DMG Game Boy 4-tone palette (default theme).
//
// Format: 0xRRGGBBAAu (SDL-style packed RGBA as uint32).
// These are intentionally non-const (inline, not constexpr) so that a theme
// asset pack or runtime configuration can overwrite them before first use.
//
// The palette is split into shell (case/bezel) and screen (LCD content) tones.
// All UI drawing in render/primitives.* and the app_render_*.ipp files
// reference these values for consistent theming.
// ---------------------------------------------------------------------------
inline std::uint32_t kShellOuterColor   = 0xC4CFA1FFu;  // case plastic     (196,207,161)
inline std::uint32_t kShellInnerColor   = 0xA5B088FFu;  // inner case       (165,176,136)
inline std::uint32_t kShellShadowColor  = 0x5A6B4AFFu;  // case shadow      (90,107,74)
inline std::uint32_t kScreenLightColor  = 0x9BBC0FFFu;  // LCD lightest     (155,188,15) — highlight
inline std::uint32_t kScreenMidColor    = 0x8BAC0FFFu;  // LCD mid          (139,172,15) — accent
inline std::uint32_t kScreenDarkColor   = 0x306230FFu;  // LCD dark         (48,98,48)   — body text
inline std::uint32_t kScreenDeepColor   = 0x0F380FFFu;  // LCD deepest      (15,56,15)   — background
inline std::uint32_t kScreenInkSoftColor= 0x4A7A2AFFu;  // soft ink         (74,122,42)  — secondary text
// Foreground text ink drawn on the app BODY (shell_inner / shell_outer /
// screen_deep expanses) — as opposed to screen_deep, which is a dark ink for
// text on BRIGHT fills (buttons, value tiles). Decoupling them lets a dark
// "terminal" theme keep true-black bodies AND bright on-body text. Themes
// that omit screen_fg inherit screen_deep (loadTheme), so every existing
// light theme is unchanged; only dark terminal themes set it bright.
inline std::uint32_t kScreenFgColor     = 0x0F380FFFu;  // on-body text ink (defaults to screen_deep)
// Interactive TILE fill — buttons, value cells, normal cue rows. Paired with
// screen_fg as the tile text. Defaults to screen_light, so light themes are
// unchanged (bright tile + dark text); a terminal theme sets it near-black
// (dark tile + bright text) for the "black tiles, green text" look.
inline std::uint32_t kScreenTileColor   = 0x9BBC0FFFu;  // tile fill (defaults to screen_light)
// Secondary on-tile / on-body text (cue-row subtext, muted labels). Paired
// with the tile fill like screen_fg, but dimmer. Defaults to screen_dark so
// light themes keep dark subtext on bright rows; terminal themes set it a
// muted-bright accent so subtext reads on dark tiles.
inline std::uint32_t kScreenFgSoftColor = 0x306230FFu;  // secondary tile ink (defaults to screen_dark)
inline std::uint32_t kButtonBezelColor  = 0x7B8B5EFFu;  // button rim       (123,139,94)
inline std::uint32_t kDeleteBezelColor  = 0x8B3A3AFFu;  // danger red bezel (139,58,58)  — delete actions

// ---------------------------------------------------------------------------
// Per-cue audio gain trim range (dB).
//
// SINGLE SOURCE OF TRUTH. This range used to be six independent literal
// `std::clamp(x, -24.0, 12.0)` calls — the setter, the loudness normalizer,
// the waveform scaler, the engine's atomic mirror, and project load. Widening
// any one of them left the others clamping the value straight back, which
// looks exactly like "normalize is broken". Every clamp now reads these.
//
// The old +12 dB ceiling was arbitrary and made loudness-normalize unable to
// reach target on quiet material (a -40 LUFS transfer needs +24 dB).
// ---------------------------------------------------------------------------
constexpr float kCueAudioGainMinDb = -40.0f;
constexpr float kCueAudioGainMaxDb =  40.0f;

// Loudness-normalize target. Normalize ALWAYS reaches this — the true-peak
// ceiling below is the deck limiter's threshold and a reporting threshold, NOT
// a cap on the gain. Capping the gain by peak headroom is what made normalize
// useless on real material: TV/film runs an 18-22 dB peak-to-loudness ratio, so
// the cap bound on every clip and a quiet cartoon that wanted +10.8 dB got
// +3.9. Peaks are MediaEngine::applyPeakLimiter's job now.
constexpr double kNormalizeTargetLufsDefault = -16.0;
constexpr double kNormalizeTruePeakCeilingDb = -1.0;

// ---------------------------------------------------------------------------
// Super Deckboy gate.
//
// Features that SPAN MULTIPLE OUTPUTS — the shared canvas, span/duplicate
// layout, and output mirroring — belong to the planned "Super Deckboy"
// multi-deck/multi-output mode. Until that mode exists they stay compiled and
// serialised (so saved shows round-trip untouched) but their UI is HIDDEN:
// showing an operator a control whose behaviour depends on a mode that isn't
// finished is worse than not showing it at all.
//
// Streaming is deliberately NOT gated by this — it is not a spanning output, it
// simply receives the program output.
//
// Flip to true when Super Deckboy work begins; grep this name to find every
// parked surface.
constexpr bool kSuperDeckboySpanningUi = false;

// ---------------------------------------------------------------------------
// Layout system — grid-based spacing constants used by render/layout.hpp.
//
// All panels, buttons, and text insets snap to multiples of kLayoutSpacingUnit
// (8px grid). This ensures consistent vertical rhythm and alignment.
// ---------------------------------------------------------------------------
// Layout constants are mutable at runtime because Project::uiScale rebuilds
// them at boot and on every UI-scale change (see App::rebuildLayoutMetrics).
// The *Base values are the immutable 1.0x baselines; rendering code should
// read the live (non-Base) names, which are inline globals updated in place.
constexpr int kLayoutSpacingUnitBase     = 8;
constexpr int kLayoutPanelPaddingBase    = 16;
constexpr int kLayoutPanelGapBase        = 12;
constexpr int kLayoutPanelBorderBase     = 2;
constexpr int kLayoutTextInsetBase       = 12;
constexpr int kLayoutHeaderHeightBase    = 56;
constexpr int kLayoutBottomBarHeightBase = 132;
constexpr int kLayoutButtonHeightBase    = 48;
constexpr int kLayoutButtonPaddingBase   = 12;
constexpr int kLayoutButtonGapBase       = 8;

// Live (scaled) layout values. `inline` (C++17) gives one definition across
// TUs while still allowing runtime mutation by App::rebuildLayoutMetrics.
// Existing call sites read these names unchanged from the pre-scale era.
inline int kLayoutSpacingUnit     = kLayoutSpacingUnitBase;
inline int kLayoutPanelPadding    = kLayoutPanelPaddingBase;
inline int kLayoutPanelGap        = kLayoutPanelGapBase;
inline int kLayoutPanelBorder     = kLayoutPanelBorderBase;
inline int kLayoutTextInset       = kLayoutTextInsetBase;
inline int kLayoutHeaderHeight    = kLayoutHeaderHeightBase;
inline int kLayoutBottomBarHeight = kLayoutBottomBarHeightBase;
inline int kLayoutButtonHeight    = kLayoutButtonHeightBase;
inline int kLayoutButtonPadding   = kLayoutButtonPaddingBase;
inline int kLayoutButtonGap       = kLayoutButtonGapBase;

// ---------------------------------------------------------------------------
// App identity strings — title bar, version display, about dialog.
//
// kAppVersion and kAppVersionTag are forwarded from the CMake-generated
// deckboy_version.hpp (sourced from the VERSION file at project root).
// ---------------------------------------------------------------------------
constexpr std::string_view kAppTitle = "Deckboy";
constexpr std::string_view kOutputTitle = "Deckboy Output";
constexpr std::string_view kAppVersion = deckboy::core::version::kVersion;
constexpr std::string_view kAppVersionTag = deckboy::core::version::kVersionTag;

#endif
