#!/usr/bin/env python3
"""Render the free test-pattern kit that the site gives away.

Deckboy generates these live at any raster and refresh, which is the point of
having them in a cue player at all. The files exist for the people who do not
have Deckboy yet -- an engineer who needs bars on a screen in the next ten
minutes is not going to install anything first, and a test card that is free
and actually useful is a better introduction than a feature list.

SOME OF THESE CANNOT BE STILLS. A frame counter is one number forever in a
PNG, and a latency clock photographed on two screens shows the same frozen
number on both -- so as stills they do not merely lose something, they cannot
do the job they exist for. The first version of this kit shipped them as PNGs
anyway, with captions describing what they would do if they moved. Anything
whose diagnostic IS the movement is rendered here as a video loop instead.

Every card is on the safe list: nothing generated by this script may show
anything `tools/audit_spoilers.py` protects. Check the FORBIDDEN table before
adding a pattern id, and LOOK at the result -- that audit reads text, it
cannot see a picture.

Run:  python tools/build_test_patterns.py
      python tools/build_test_patterns.py --exe path\\to\\Deckboy.exe
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "patterns"
ZIP_NAME = "deckboy-test-patterns.zip"

WIDTH, HEIGHT = 1920, 1080
STILL_AT = 3          # seconds, for the patterns that do not move
LOOP_SECONDS = 10
LOOP_FPS = 25

# id, stem, kind, and the fault it is for.
#
#   still   a PNG is the whole thing
#   motion  the diagnostic IS the movement; a PNG cannot do it
#   both    a good card standing still, better moving
PATTERNS = [
    ("smpte-bars", "smpte-bars", "still",
     "Colour and levels. The pluge strip below the bars is the one that tells "
     "you whether black is really black on that screen."),
    ("crosshatch", "crosshatch", "still",
     "Geometry and convergence. Straight lines go bent long before a picture "
     "looks wrong, and the safe-area box shows what a projector is eating."),
    ("checkerboard", "checkerboard", "still",
     "Scaling and overscan. A scaler that is not running 1:1 turns the "
     "squares into moire the moment you look at it."),
    ("pocket-test", "pocket-test", "both",
     "The whole chain on one card: bars, a grey staircase and geometry. The "
     "video also carries a moving element, so a frozen frame cannot pretend "
     "to be a live one -- which the still, by definition, cannot show you."),
    ("latency-clock", "latency-clock", "motion",
     "Latency, measured. Play it on two screens, photograph both in one shot, "
     "and read the difference off the counters."),
    ("frame-count", "frame-count", "motion",
     "Dropped and repeated frames. Shoot it at a high shutter and count: any "
     "number that appears twice, or not at all, is a frame that did not make it."),
    ("pocket-day", "picture-day", "still",
     "A real picture rather than a chart -- gradients, fine detail and "
     "saturated flats together, which is where banding and posterisation show."),
    ("pocket-night", "picture-night", "still",
     "The same picture at night, for black level and shadow detail. A screen "
     "that looked fine on bars can still crush everything below 10%."),
]


def find_exe(explicit):
    if explicit:
        return Path(explicit)
    for candidate in (
        ROOT / "build" / "windows" / "Release" / "Deckboy.exe",
        ROOT / "build" / "Deckboy",
        ROOT / "build" / "deckboy",
    ):
        if candidate.exists():
            return candidate
    return None


def find_ffmpeg(exe):
    """Deckboy ships ffmpeg beside itself; fall back to one on PATH."""
    beside = exe.parent / ("ffmpeg.exe" if os.name == "nt" else "ffmpeg")
    if beside.exists():
        return beside
    for staged in sorted((ROOT / "dist" / "staging").glob("*/ffmpeg*"), reverse=True):
        if staged.is_file():
            return staged
    found = shutil.which("ffmpeg")
    return Path(found) if found else None


def dump(exe, env, pattern_id, target, seconds):
    subprocess.run(
        [str(exe), "--pattern-dump", pattern_id, str(target),
         "%dx%d" % (WIDTH, HEIGHT), str(seconds)],
        env=env, capture_output=True, text=True)
    return target.exists()


def render_still(exe, env, pattern_id, stem, scratch, Image):
    ppm = scratch / (stem + ".ppm")
    if not dump(exe, env, pattern_id, ppm, STILL_AT):
        return None
    png = OUT / (stem + ".png")
    Image.open(ppm).convert("RGB").save(png, optimize=True)
    ppm.unlink()
    return png


def render_loop(exe, env, ffmpeg, pattern_id, stem, scratch):
    """A video, because this pattern's whole diagnostic is that it moves."""
    frames = scratch / (stem + "-frames")
    frames.mkdir(parents=True, exist_ok=True)
    total = LOOP_SECONDS * LOOP_FPS
    for index in range(total):
        target = frames / ("%05d.ppm" % index)
        if not dump(exe, env, pattern_id, target, index / float(LOOP_FPS)):
            print("  %s failed at frame %d" % (pattern_id, index))
            return None
    mp4 = OUT / (stem + ".mp4")
    if mp4.exists():
        mp4.unlink()
    result = subprocess.run(
        [str(ffmpeg), "-nostdin", "-loglevel", "error",
         "-framerate", str(LOOP_FPS), "-i", str(frames / "%05d.ppm"),
         "-c:v", "libx264", "-preset", "slow", "-crf", "18",
         "-pix_fmt", "yuv420p", "-movflags", "+faststart",
         str(mp4)],
        capture_output=True, text=True)
    shutil.rmtree(frames, ignore_errors=True)
    if result.returncode != 0 or not mp4.exists():
        print("  ffmpeg failed: " + (result.stderr or result.stdout).strip()[:300])
        return None

    # A poster, so the card on the page is not a black rectangle before the
    # video loads. Kept out of the download list on purpose: it is the frame
    # the video starts on, not a still anybody should be testing with.
    posters = OUT / "posters"
    posters.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [str(ffmpeg), "-nostdin", "-loglevel", "error", "-y",
         "-i", str(mp4), "-frames:v", "1", str(posters / (stem + ".png"))],
        capture_output=True, text=True)
    return mp4


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--exe", help="path to the Deckboy binary")
    args = parser.parse_args()

    exe = find_exe(args.exe)
    if not exe or not exe.exists():
        print("no Deckboy binary found -- build one, or pass --exe")
        return 1
    ffmpeg = find_ffmpeg(exe)
    if not ffmpeg:
        print("no ffmpeg found, and half this kit is video")
        return 1

    try:
        from PIL import Image
    except ImportError:
        print("Pillow is needed to write the PNGs: pip install pillow")
        return 1

    OUT.mkdir(parents=True, exist_ok=True)
    scratch = Path(tempfile.mkdtemp(prefix="deckboy-patterns-"))
    # The app must not touch the real show or settings while doing this.
    env = dict(os.environ, DECKBOY_STATE_DIR=str(scratch / "state"))

    written = []
    try:
        for pattern_id, stem, kind, _ in PATTERNS:
            if kind in ("still", "both"):
                png = render_still(exe, env, pattern_id, stem, scratch, Image)
                if not png:
                    print("  %s did not render" % pattern_id)
                    return 1
                written.append(png)
                print("  %-22s %6.0f KB" % (png.name, png.stat().st_size / 1024))
            if kind in ("motion", "both"):
                print("  %-22s rendering %d frames..." % (stem + ".mp4",
                                                          LOOP_SECONDS * LOOP_FPS))
                mp4 = render_loop(exe, env, ffmpeg, pattern_id, stem, scratch)
                if not mp4:
                    return 1
                written.append(mp4)
                print("  %-22s %6.0f KB" % (mp4.name, mp4.stat().st_size / 1024))
    finally:
        shutil.rmtree(scratch, ignore_errors=True)

    archive = OUT / ZIP_NAME
    if archive.exists():
        archive.unlink()
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as bundle:
        for item in written:
            bundle.write(item, item.name)
        bundle.writestr("README.txt", readme())

    total = sum(p.stat().st_size for p in written) + archive.stat().st_size
    print("%d files, %.1f MB in total" % (len(written), total / 1048576))
    return 0


def readme():
    lines = [
        "Deckboy test patterns",
        "=====================",
        "",
        "Free to use for anything. Stills are %dx%d PNG; the moving ones are"
        % (WIDTH, HEIGHT),
        "%d-second H.264 at %d fps, because their whole diagnostic is that they"
        % (LOOP_SECONDS, LOOP_FPS),
        "move -- a frame counter in a still is one number forever.",
        "",
    ]
    for _, stem, kind, why in PATTERNS:
        names = []
        if kind in ("still", "both"):
            names.append(stem + ".png")
        if kind in ("motion", "both"):
            names.append(stem + ".mp4")
        lines.append(" and ".join(names))
        lines.append("    " + " ".join(why.split()))
        lines.append("")
    lines += [
        "These were generated by Deckboy, which makes them live at whatever",
        "raster and refresh the output is running, so you never need a file.",
        "",
        "https://utopian-academy.github.io/Deckboy/",
    ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    sys.exit(main())
