#!/usr/bin/env python3
"""Render the free test-pattern kit that the site gives away.

Deckboy generates these live at any raster and refresh, which is the point of
having them in a cue player at all. The files exist for the people who do not
have Deckboy yet -- an engineer who needs bars on a screen in the next ten
minutes is not going to install anything first, and a test card that is free
and actually useful is a better introduction than a feature list.

Every card here is on the safe list: nothing generated by this script may show
anything `tools/audit_spoilers.py` protects. Check the FORBIDDEN table before
adding a pattern id, and LOOK at the result -- that audit reads text, it
cannot see a picture.

Run:  python tools/build_test_patterns.py
      python tools/build_test_patterns.py --exe path\\to\\Deckboy.exe
"""

import argparse
import os
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "patterns"
ZIP_NAME = "deckboy-test-patterns.zip"

# id, file stem, and the fault it is for. The third column is the reason the
# card is in the kit; if it cannot be written, the card does not belong.
PATTERNS = [
    ("smpte-bars", "smpte-bars",
     "Colour and levels. The pluge strip below the bars is the one that tells "
     "you whether black is really black on that screen."),
    ("crosshatch", "crosshatch",
     "Geometry and convergence. Straight lines go bent long before a picture "
     "looks wrong, and the safe-area box shows what a projector is eating."),
    ("checkerboard", "checkerboard",
     "Scaling and overscan. A scaler that is not running 1:1 turns the "
     "squares into moire the moment you look at it."),
    ("pocket-test", "pocket-test",
     "The whole chain on one card: bars, a grey staircase, geometry, and a "
     "moving element so a frozen frame cannot pretend to be a live one."),
    ("latency-clock", "latency-clock",
     "Latency, measured. Put it on two screens, photograph both, and read "
     "the difference -- the counter is exact, not a spinning wheel."),
    ("frame-count", "frame-count",
     "Dropped and repeated frames. Shoot it at a high shutter and count: any "
     "number that appears twice, or not at all, is a frame that did not make it."),
    ("pocket-day", "picture-day",
     "A real picture rather than a chart -- gradients, fine detail and "
     "saturated flats together, which is where banding and posterisation show."),
    ("pocket-night", "picture-night",
     "The same picture at night, for black level and shadow detail. A screen "
     "that looked fine on bars can still crush everything below 10%."),
]

WIDTH, HEIGHT, AT_SECONDS = 1920, 1080, 3


def find_exe(explicit):
    if explicit:
        return Path(explicit)
    for candidate in (
        ROOT / "build" / "windows" / "Release" / "Deckboy.exe",
        ROOT / "build" / "Deckboy",
        ROOT / "build" / "deckboy",
    ):
        if candidate.exists():
            return candidate
    return None


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--exe", help="path to the Deckboy binary")
    args = parser.parse_args()

    exe = find_exe(args.exe)
    if not exe or not exe.exists():
        print("no Deckboy binary found -- build one, or pass --exe")
        return 1

    try:
        from PIL import Image
    except ImportError:
        print("Pillow is needed to write the PNGs: pip install pillow")
        return 1

    OUT.mkdir(parents=True, exist_ok=True)
    scratch = Path(tempfile.mkdtemp(prefix="deckboy-patterns-"))
    # The app must not touch the real show or settings while doing this.
    env = dict(os.environ, DECKBOY_STATE_DIR=str(scratch / "state"))

    written = []
    for pattern_id, stem, _ in PATTERNS:
        ppm = scratch / (stem + ".ppm")
        result = subprocess.run(
            [str(exe), "--pattern-dump", pattern_id, str(ppm),
             "%dx%d" % (WIDTH, HEIGHT), str(AT_SECONDS)],
            env=env, capture_output=True, text=True)
        if not ppm.exists():
            print("%s did not render: %s" % (pattern_id, result.stdout.strip()
                                             or result.stderr.strip()))
            return 1
        png = OUT / (stem + ".png")
        Image.open(ppm).convert("RGB").save(png, optimize=True)
        written.append(png)
        print("  %-16s %5.0f KB" % (png.name, png.stat().st_size / 1024))

    # One download for somebody who wants the lot on a stick.
    archive = OUT / ZIP_NAME
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as bundle:
        for png in written:
            bundle.write(png, png.name)
        bundle.writestr("README.txt", readme())
    print("  %-16s %5.0f KB" % (archive.name, archive.stat().st_size / 1024))

    total = sum(p.stat().st_size for p in written) + archive.stat().st_size
    print("%d cards, %.0f KB in total" % (len(written), total / 1024))
    return 0


def readme():
    lines = [
        "Deckboy test patterns",
        "=====================",
        "",
        "%d cards at %dx%d, free to use for anything." % (len(PATTERNS), WIDTH, HEIGHT),
        "",
    ]
    for _, stem, why in PATTERNS:
        lines.append("%s.png" % stem)
        lines.append("    " + " ".join(why.split()))
        lines.append("")
    lines += [
        "These were generated by Deckboy, which makes them live at whatever",
        "raster and refresh the output is running, so you never need a file.",
        "",
        "https://utopian-academy.github.io/Deckboy/",
    ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    sys.exit(main())
