#!/usr/bin/env python3
"""Generate native/core/bidi_data.inc from the Unicode Character Database.

    python tools/gen_bidi_tables.py <ucd-dir> [native/core/bidi_data.inc]

<ucd-dir> holds DerivedBidiClass.txt (from extracted/) and BidiBrackets.txt,
both from https://www.unicode.org/Public/<version>/ucd/. The output is a sorted
range table of every code point's Bidi_Class and the list of paired brackets,
which is everything native/core/bidi.cpp needs and nothing it does not.

Generated rather than written by hand because the bidi class of a character is
data, not judgement: a hand-kept table is right for the scripts its author
thought of and quietly wrong for the rest, and it ages with every Unicode
release. Re-run this when Unicode publishes a new version; the conformance
check (tools/bidi_check.cpp) then says whether anything moved.
"""

import os
import re
import sys

# The order is the enum's in bidi.hpp. Changing one without the other makes
# every class in the table wrong at once, which the conformance check catches.
CLASSES = ["L", "R", "AL", "EN", "ES", "ET", "AN", "CS", "NSM", "BN", "B", "S",
           "WS", "ON", "LRE", "LRO", "RLE", "RLO", "PDF", "LRI", "RLI", "FSI", "PDI"]

LONG_NAMES = {
    "Left_To_Right": "L", "Right_To_Left": "R", "Arabic_Letter": "AL",
    "European_Number": "EN", "European_Separator": "ES",
    "European_Terminator": "ET", "Arabic_Number": "AN",
    "Common_Separator": "CS", "Nonspacing_Mark": "NSM",
    "Boundary_Neutral": "BN", "Paragraph_Separator": "B",
    "Segment_Separator": "S", "White_Space": "WS", "Other_Neutral": "ON",
    "Left_To_Right_Embedding": "LRE", "Left_To_Right_Override": "LRO",
    "Right_To_Left_Embedding": "RLE", "Right_To_Left_Override": "RLO",
    "Pop_Directional_Format": "PDF", "Left_To_Right_Isolate": "LRI",
    "Right_To_Left_Isolate": "RLI", "First_Strong_Isolate": "FSI",
    "Pop_Directional_Isolate": "PDI",
}

MAX_CP = 0x10FFFF


def short(name):
    name = name.strip()
    return LONG_NAMES.get(name, name)


def parse_range(text):
    if ".." in text:
        a, b = text.split("..")
        return int(a, 16), int(b, 16)
    v = int(text, 16)
    return v, v


def read_version(path):
    with open(path, encoding="utf-8") as f:
        first = f.readline()
    m = re.search(r"-(\d+\.\d+\.\d+)\.txt", first)
    return m.group(1) if m else "unknown"


def build_classes(path):
    cls = bytearray([CLASSES.index("L")]) * (MAX_CP + 1)
    explicit = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            # Defaults for code points no line names: the general L first, then
            # the blocks set aside for right-to-left scripts, in file order, so
            # a later and narrower @missing wins -- which is how the file says
            # to read them.
            m = re.match(r"#\s*@missing:\s*([0-9A-Fa-f.]+)\s*;\s*(\w+)", line)
            if m:
                a, b = parse_range(m.group(1))
                v = CLASSES.index(short(m.group(2)))
                cls[a:b + 1] = bytes([v]) * (b - a + 1)
                continue
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            field, value = [x.strip() for x in line.split(";")[:2]]
            explicit.append((parse_range(field), CLASSES.index(short(value))))
    for (a, b), v in explicit:
        cls[a:b + 1] = bytes([v]) * (b - a + 1)
    return cls


def ranges(cls):
    out = []
    start = 0
    for cp in range(1, MAX_CP + 2):
        if cp == MAX_CP + 1 or cls[cp] != cls[start]:
            out.append((start, cp - 1, cls[start]))
            start = cp
    return out


def brackets(path):
    out = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            a, b, kind = [x.strip() for x in line.split(";")]
            out.append((int(a, 16), int(b, 16), kind == "o"))
    return sorted(out)


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    ucd = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "native", "core", "bidi_data.inc")
    classes_file = os.path.join(ucd, "DerivedBidiClass.txt")
    brackets_file = os.path.join(ucd, "BidiBrackets.txt")
    version = read_version(classes_file)
    if read_version(brackets_file) != version:
        sys.exit("DerivedBidiClass.txt and BidiBrackets.txt are from different Unicode versions")
    table = ranges(build_classes(classes_file))
    pairs = brackets(brackets_file)

    lines = []
    lines.append("// GENERATED by tools/gen_bidi_tables.py from the Unicode Character")
    lines.append("// Database %s (DerivedBidiClass.txt, BidiBrackets.txt). Do not edit by" % version)
    lines.append("// hand: re-run the generator against a newer UCD instead.")
    lines.append("//")
    lines.append("// Unicode data: Copyright (c) 1991-2026 Unicode, Inc. Distributed under the")
    lines.append("// Unicode License v3, https://www.unicode.org/license.txt")
    lines.append("")
    lines.append('constexpr const char* kUnicodeVersion = "%s";' % version)
    lines.append("")
    lines.append("// [first, last, class] -- every code point, sorted, adjacent equal classes merged.")
    lines.append("constexpr BidiRange kBidiRanges[] = {")
    for a, b, v in table:
        lines.append("  {0x%04X, 0x%04X, BidiClass::%s}," % (a, b, CLASSES[v]))
    lines.append("};")
    lines.append("")
    lines.append("// [code point, its pair, opening?] -- Bidi_Paired_Bracket and its type, sorted.")
    lines.append("constexpr BidiBracket kBidiBrackets[] = {")
    for a, b, opening in pairs:
        lines.append("  {0x%04X, 0x%04X, %s}," % (a, b, "true" if opening else "false"))
    lines.append("};")
    lines.append("")
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print("Unicode %s: %d ranges, %d brackets -> %s" % (version, len(table), len(pairs), out_path))


if __name__ == "__main__":
    main()
